version: "3.7"

services:
  django:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - 8000:8000
    volumes:
      - .:/web/app
    command: python manage.py runserver 0.0.0.0:8000

  postgresql:
    image: postgres:13.4-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: