version: "3.7"

services:
  django:
    build: .
    context: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgresql
    expose:
      - 8000
    volumes:
      - .:/web/app

  postgresql:
    image: postgres:13.4-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: