# Generated by Django 3.2.6 on 2021-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortened_link', models.URLField(blank=True, null=True, unique=True)),
                ('owner_ip', models.GenericIPAddressField()),
                ('shorten_try', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
