# Generated by Django 3.2.6 on 2021-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenlink',
            name='shortened_link',
        ),
        migrations.AddField(
            model_name='shortenlink',
            name='shortened_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
