# Generated by Django 3.2.6 on 2021-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_shortened_slug_shortenlink_shorten_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenlink',
            name='url',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
